### ISSUE TITLE
[Wiki] Fix compiler option

### ISSUE THREAD

**Issue by akakou** [IBM/libgroupsig#17]
I read the [wiki](https://github.com/IBM/libgroupsig/wiki/Using-libgroupsig#signing-in-c) and I have some questions.

- Does it forget the source file of the compiler option?
- Is the linked library really cml?

### Now
> gcc -o sign_gl19 -lgroupsig -lcml -Wl,-rpath=/usr/local/lib

### I guess
> gcc sign_gl19.c -o sign_gl19 -lgroupsig -lmcl -Wl,-rpath=/usr/local/lib

**Comment by jdv-ibm** [comment]
Indeed, you are right in both comments. Typos fixed. Thanks for the review!
