### ISSUE TITLE
[Wiki] Is the wrappers source code path right?

### ISSUE THREAD

**Issue by akakou** [IBM/libgroupsig#18]
I read the [wiki](https://github.com/IBM/libgroupsig/wiki/Building-libgroupsig#build-python-wrapper-pygroupsig) and I have a question.

It written as `src/ports/<language>`, but not exists. 
So I guess it point to `src/wrappers/<language>`, is it right?

**Comment by jdv-ibm** [comment]
Yes, it is wrappers. Fixed. Thanks for spotting it!
