### ISSUE TITLE
[Core] hash_get does not seem correct

### ISSUE THREAD

**Issue by jesusdiazvico** [IBM/libgroupsig#36]
The [hash_get function](https://github.com/IBM/libgroupsig/blob/7e9fb8b2011075ba413fec1869c6f6c0bbd82b22/src/shim/hash.c#L117) should interface the EVP_Digest from OpenSSL (currently, it only does EVP_DigestInit and EVP_DigestUpdate). 

Currently, it is not used by any scheme (schemes use the Init-Update-Finalize interface). But check and add tests.

**Comment by jdv-ibm** [comment]
Fixed in commit 1c18149654f44c2880e021f923c6551b4a5f3e11.
