### ISSUE TITLE
[NodeJS] Add cert field in sample REST server join request

### ISSUE THREAD

**Issue by jesusdiazvico** [IBM/libgroupsig#39]
When requesting to join a group, it is common that prospective members add (and prove control of) a certificate from some common PKI. 

Add this field to the first message sent by the prospective member, which would be:
- The message in the [`POST /group/:groupId/member`](https://github.com/IBM/libgroupsig/blob/19bb9c622a1765af29e060ff1a9f125c019e3af8/src/wrappers/nodejs/server/src/routes/group.js#L243) API endpoint, if the party initiating the protocol is the Group Manager.
- The message in the [`/group/:groupId/member/2`](https://github.com/IBM/libgroupsig/blob/19bb9c622a1765af29e060ff1a9f125c019e3af8/src/wrappers/nodejs/server/src/routes/group.js#L314) API endpoint, if the party initiating the protocol is the prospective member.

**Comment by jdv-ibm** [comment]
Fixed in commit d9c2c1e2e28e08dd8f449d2874daa590397bb730 (develop branch). Will merge to master in next release.
