### ISSUE TITLE
GL19 and GML

### ISSUE THREAD

**Issue by donovano** [IBM/libgroupsig#46]
Hi,

groupsig_open requires a valid initialized GML, and it looks like in your library only schemes bbs04, ps16 and klap20 have implementations for GML. With scheme GL19 it appears not possible to obtain a GML. Thus with GL19 one cannot call groupsig_open and the identity thus cannot be revealed. 

Is this just a gap in your library and you still need to implement this for GL19 or is it the case that scheme GL19 does not allow for obtaining the identity from the GML like with the other schemes?

Thanks

**Comment by jdv-ibm** [comment]
Hi,

GL19 does not support opening. You can check this in the [paper](https://eprint.iacr.org/2019/027.pdf) (there is no open functionality described in the Syntax section (3.1)); or in the implementation in this library (the [`open` function pointer](https://github.com/IBM/libgroupsig/blob/f95ea349da73e68f38337a9bcbf4219b46e28456/src/include/gl19.h#L350) within the groupsig handle is set to NULL, and also the [`has_gml` variable](https://github.com/IBM/libgroupsig/blob/f95ea349da73e68f38337a9bcbf4219b46e28456/src/include/gl19.h#L59) in the `groupsig_description_t` structure is set to 0 (which means that this scheme does not rely on GMLs).

In practice, this means that, of course, you cannot use open in GL19 schemes. And, in any call that requires a GML parameter (if you use the C library), that parameter is ignored (you may just set it to NULL).

Hope that helps.

**Comment by donovano** [comment]
Thanks for details. Closing.
