### ISSUE TITLE
[NodeJS] Add X-API-KEY header parameter in sample REST server

### ISSUE THREAD

**Issue by jesusdiazvico** [IBM/libgroupsig#47]
Add an X-API-KEY parameter in the header of HTTP requests for the sample REST server implemented in NodeJS.

The value of the parameter will be configurable via de .env file (currently located in the root folder of the server).

**Comment by jdv-ibm** [comment]
Merged into master in commit 2524700a1b71190f0be58bf23bdc791684901813.
